(defun add-subdirs-to-load-path (dir)
  "Recursive add directories to 'load-path'."
  (let ((default-directory (file-name-as-directory dir)))
    (add-to-list 'load-path dir)
   (normal-top-level-add-subdirs-to-load-path)))
;;把github上的文件下载到本地后，拷贝该init文件到.emacs.d中，同时将本地文件夹路径写在下述函数中即可完成emacs的配置
(add-subdirs-to-load-path "~/luopx-emacs-one-by-one")
(require 'theme)
(require 'init-startup)
(require 'lazy-set-key)
(require 'init-semx)
(require 'init-awesome-tab)
(require 'init-awesome-pair)
(require 'init-awesome-tray)
;;(require 'init-auto-save)
(require 'init-thing-edit)
(require 'init-yasnippet)
(require 'init-company-mode)
(require 'init-keys)
(require 'init-xah-fly-keys)
(require 'init-which-key)
(require 'init-dired)
